# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
pod 'Google/CloudMessaging'
target 'Ridgefield Parks and Recreation' do

end

target 'Ridgefield Parks and RecreationTests' do

end

